
package com.demo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "POApp", targetNamespace = "http://ws.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface POApp {


    /**
     * 
     * @param order
     * @return
     *     returns com.demo.ws.Invoice
     */
    @WebMethod(action = "http://ws.demo.com/submitPO")
    @WebResult(name = "invoice", targetNamespace = "")
    @RequestWrapper(localName = "submitPO", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SubmitPO")
    @ResponseWrapper(localName = "submitPOResponse", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SubmitPOResponse")
    public Invoice submitPO(
        @WebParam(name = "order", targetNamespace = "")
        Order order);

}
