
package com.demo.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpService", targetNamespace = "http://ws.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEmp", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SaveEmp")
    @ResponseWrapper(localName = "saveEmpResponse", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SaveEmpResponse")
    @Action(input = "http://ws.demo.com/EmpService/saveEmpRequest", output = "http://ws.demo.com/EmpService/saveEmpResponse")
    public String saveEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        Emp arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.demo.ws.Emp>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpList", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.GetEmpList")
    @ResponseWrapper(localName = "getEmpListResponse", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.GetEmpListResponse")
    @Action(input = "http://ws.demo.com/EmpService/getEmpListRequest", output = "http://ws.demo.com/EmpService/getEmpListResponse")
    public List<Emp> getEmpList();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.demo.ws.Emp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpDetails", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.GetEmpDetails")
    @ResponseWrapper(localName = "getEmpDetailsResponse", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.GetEmpDetailsResponse")
    @Action(input = "http://ws.demo.com/EmpService/getEmpDetailsRequest", output = "http://ws.demo.com/EmpService/getEmpDetailsResponse")
    public Emp getEmpDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
